### ISSUE TITLE
add default messages

### ISSUE THREAD

**Issue by luisrudge** [square/lgtm#16]
It's hard to type the same message every time, or even abstract to constants. Maybe we have to have some defaults?

Also, this won't work:

```js
var v = LGTM.validator().validates('name').required().build();
v.validate({foo: 'bar'}).then(function(r) {
  console.log(r); // {valid: true}
});
```

While this works: 

```js
var v = LGTM.validator().validates('name').required('any message').build();
v.validate({foo: 'bar'}).then(function(r) {
  console.log(r); // {valid: false}
});
```

**Comment by eventualbuddha** [comment]
> It's hard to type the same message every time, or even abstract to constants.

Some people use [custom helpers](https://github.com/square/lgtm/wiki/Custom-Helpers) for this. You can even override a built-in one to provide a default:

```js
LGTM.helpers.register('required', function(message="Please provide a value.") {
  this.using(function(value) {
    return value !== null && value !== undefined && value !== '';
  }, message);
});
```

As for why `required()` does not result in `valid: false`, I believe it's due to [this part of `ObjectValidator`](https://github.com/square/lgtm/blob/21a3534e36ce7af37d650e6617160e153f3c2250/src/lgtm/object_validator.js#L147-L150). The behavior is wrong, but I would argue that the right thing is to throw when no message is provided. What do you think?

**Comment by luisrudge** [comment]
Well, I still think that defaults should be provided by default and, if the user uses undefined or null as a message, then throw an useful exception

**Comment by eventualbuddha** [comment]
Tracking the issue raised in #17.
